import Navbar from '@/components/navbar/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToasterProvider from '@/providers/toaster-provider'
import ClientOnly from '@/components/ui/client-only'
import LoginModal from '@/components/modals/login-modal'
import RegisterModal from '@/components/modals/register-modal'
import getCurrentUser from '@/actions/get-current-user'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body>
        <ClientOnly>
          <LoginModal />
          <RegisterModal />
          <ToasterProvider />
        </ClientOnly>
        <Navbar currentUser={currentUser}/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
